name: Install into repository
on:
  push:
  workflow_dispatch:
  schedule:
    # nightly 10pm and the teardown workflow runs just after
    - cron: "0 22 * * *"

jobs:
  install-repo-runner:
    runs-on: ubuntu-20.04
    name: Install runner into this repository
    strategy:
      matrix:
        runner_tag: [ v1, latest ]
      fail-fast: false
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
          insecure_skip_tls_verify: true

      - name: Install self hosted runner into repository
        id: install-runners
        # uses: redhat-actions/openshift-actions-runner-installer@v1
        # Test the checked-out version of this runner - a user would need the above 'uses'.
        uses: ./
        with:
          # This token has 'repo' permissions
          github_pat: ${{ secrets.REPO_TOKEN }}

          helm_release_name: node-${{ matrix.runner_tag }}-runner

          # Give the runner these two labels (which are required by the workflow below)
          runner_labels: node

          # Use this container image for the runner.
          runner_image: quay.io/redhat-github-actions/node-runner-14

          # Use this tag for the runner_image
          runner_tag: ${{ matrix.runner_tag }}

          helm_extra_args: |
            --set-string secretName=github-pat-repo-${{ matrix.runner_tag }}

          # Create 2 replicas so we can run jobs in parallel
          runner_replicas: 2

      - name: Echo outputs
        shell: bash
        run: |
          echo "${{ toJSON(steps.install-runners.outputs) }}"

  dispatch:
    name: Dispatch another workflow
    runs-on: ubuntu-20.04
    needs: install-repo-runner

    steps:
      - uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          # See ./dispatched_example.yml for the type to use.
          event-type: runner_ready

  test-selfhosted:
    name: Self Hosted Node Workflow
    runs-on: [ self-hosted, node ]
    needs: install-repo-runner

    steps:
      - run: node --version
      - run: npm --version
